osx_image: xcode8.2
language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
script:
    - |
      xctool run-tests \
      -project LeetCode.xcodeproj \
      -scheme LeetCodeTests \
      -sdk macosx
